version: '3.6'
services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    # volumes:
    #   - ./mariadb/initdb/:/docker-entrypoint-initdb.d
    #   - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=dstb
      - MYSQL_DATABASE=dstb_db
      - MYSQL_USER=dstb
      - MYSQL_PASSWORD=dstb
    networks:
      - default

  pma:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    networks:
      - default

  jupyterlab:
    image: andreper/jupyterlab:2.1.4-spark-2.4.4
    container_name: jupyterlab
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace

    networks:
      - default
  
  spark-master:
    image: andreper/spark-master:2.4.4-hadoop-2.7
    container_name: spark-master
    restart: unless-stopped
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace

    networks:
      - default

  spark-worker-1:
    image: andreper/spark-worker:2.4.4-hadoop-2.7
    container_name: spark-worker-1
    restart: unless-stopped
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

    networks:
      - default

  spark-worker-2:
    image: andreper/spark-worker:2.4.4-hadoop-2.7
    container_name: spark-worker-2
    restart: unless-stopped
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

    networks:
      - default
    
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

networks:
  default:
    external:
      name:
        web_network